import { NextResponse } from "next/server";

const members = [
    {
        id: 1,
        firstName: "Church",
        lastName: "Admin",
        email: "admin@church.com",
        homePhone: "",
        cellPhone: "",
        gender: "Unassigned",
        classification: "Unassigned",
        role: "Administrator",
    },
    {
        id: 2,
        firstName: "John",
        lastName: "Doe",
        email: "john@example.com",
        homePhone: "555-1111",
        cellPhone: "999-8888",
        gender: "Male",
        classification: "Member",
        role: "Usher",
    },
    // --- Generated Data Starts Here (ID 3 to 20) ---
    {
        id: 3,
        firstName: "Sarah",
        lastName: "Connor",
        email: "sarah.c@church.org",
        homePhone: "555-2345",
        cellPhone: "999-1234",
        gender: "Female",
        classification: "Associate Member",
        role: "Worship Team",
    },
    {
        id: 4,
        firstName: "Michael",
        lastName: "Brown",
        email: "mike.b@church.org",
        homePhone: "",
        cellPhone: "777-4567",
        gender: "Male",
        classification: "Member",
        role: "Deacon",
    },
    {
        id: 5,
        firstName: "Jessica",
        lastName: "Alvarez",
        email: "jess.a@church.org",
        homePhone: "555-8765",
        cellPhone: "999-9012",
        gender: "Female",
        classification: "Visitor",
        role: "Unassigned",
    },
    {
        id: 6,
        firstName: "David",
        lastName: "Lee",
        email: "dave.lee@church.org",
        homePhone: "555-3333",
        cellPhone: "888-2222",
        gender: "Male",
        classification: "Member",
        role: "Youth Leader",
    },
    {
        id: 7,
        firstName: "Emily",
        lastName: "Clark",
        email: "emily.c@church.org",
        homePhone: "",
        cellPhone: "666-5432",
        gender: "Female",
        classification: "Member",
        role: "Children's Ministry",
    },
    {
        id: 8,
        firstName: "Robert",
        lastName: "Green",
        email: "robert.g@church.org",
        homePhone: "555-6789",
        cellPhone: "",
        gender: "Male",
        classification: "Member",
        role: "Elder",
    },
    {
        id: 9,
        firstName: "Linda",
        lastName: "Martinez",
        email: "linda.m@church.org",
        homePhone: "555-0011",
        cellPhone: "999-0011",
        gender: "Female",
        classification: "Non-Attending Member",
        role: "Unassigned",
    },
    {
        id: 10,
        firstName: "James",
        lastName: "Taylor",
        email: "james.t@church.org",
        homePhone: "555-5555",
        cellPhone: "777-7777",
        gender: "Male",
        classification: "Member",
        role: "Technical Support",
    },
    {
        id: 11,
        firstName: "Patricia",
        lastName: "Wilson",
        email: "patricia.w@church.org",
        homePhone: "",
        cellPhone: "666-1212",
        gender: "Female",
        classification: "Member",
        role: "Finance Team",
    },
    {
        id: 12,
        firstName: "Daniel",
        lastName: "Garcia",
        email: "daniel.g@church.org",
        homePhone: "555-4040",
        cellPhone: "888-3030",
        gender: "Male",
        classification: "Member",
        role: "Sound Engineer",
    },
    {
        id: 13,
        firstName: "Maria",
        lastName: "Rodriguez",
        email: "maria.r@church.org",
        homePhone: "555-9090",
        cellPhone: "",
        gender: "Female",
        classification: "Associate Member",
        role: "Sunday School Teacher",
    },
    {
        id: 14,
        firstName: "Chris",
        lastName: "Harris",
        email: "chris.h@church.org",
        homePhone: "",
        cellPhone: "999-4444",
        gender: "Male",
        classification: "Visitor",
        role: "Unassigned",
    },
    {
        id: 15,
        firstName: "Anna",
        lastName: "Scott",
        email: "anna.s@church.org",
        homePhone: "555-1200",
        cellPhone: "888-1200",
        gender: "Female",
        classification: "Member",
        role: "Missions Team",
    },
    {
        id: 16,
        firstName: "Paul",
        lastName: "Baker",
        email: "paul.b@church.org",
        homePhone: "555-7070",
        cellPhone: "",
        gender: "Male",
        classification: "Member",
        role: "Custodian",
    },
    {
        id: 17,
        firstName: "Laura",
        lastName: "King",
        email: "laura.k@church.org",
        homePhone: "",
        cellPhone: "666-5050",
        gender: "Female",
        classification: "Member",
        role: "Small Group Leader",
    },
    {
        id: 18,
        firstName: "Kevin",
        lastName: "Lopez",
        email: "kevin.l@church.org",
        homePhone: "555-2020",
        cellPhone: "999-3030",
        gender: "Male",
        classification: "Member",
        role: "Security Team",
    },
    {
        id: 19,
        firstName: "Nicole",
        lastName: "Adams",
        email: "nicole.a@church.org",
        homePhone: "555-1999",
        cellPhone: "777-1999",
        gender: "Female",
        classification: "Non-Attending Member",
        role: "Unassigned",
    },
    {
        id: 20,
        firstName: "George",
        lastName: "White",
        email: "george.w@church.org",
        homePhone: "",
        cellPhone: "888-6666",
        gender: "Male",
        classification: "Member",
        role: "Deacon",
    },
    {
        id: 21,
        firstName: "Robin",
        lastName: "edward",
        email: "robin.w@church.org",
        homePhone: "",
        cellPhone: "666-7777",
        gender: "Male",
        classification: "visitor",
        role: "security team",
    },
];

export async function GET() {
    return NextResponse.json(members);
}

// POST new member
export async function POST(req: Request) {
    const data = await req.json();
    const newMember = { id: Date.now(), ...data };
    members.push(newMember);
    return NextResponse.json({ message: "Member added", member: newMember });
}
